version: "3.9"

services:
  web:
    build: .
    container_name: dmbe
    ports:
      - "8000:8000"
    volumes:
      - .:/dmbe
      - ./devices.db:/dmbe/devices.db
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./devices.db
    restart: always
