permissions:
  admin:
    - manage_users
    - manage_devices
    - manage_jobs
    - view_everything

  operator:
    - manage_jobs
    - view_devices

  user:
    - view_devices

inheritance:
  admin:
    - operator
    - user

  operator:
    - user

  user: []

commands:
  admin:
    cisco:
      ios:
        router:
          - show version
          - show ip route
        switch:
          - show version
          - show interface status

      nxos:
        switch:
          - show version
          - show module

  operator:
    cisco:
      ios:
        router:
          - show version
        switch:
          - show version


